i# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "flex_lowflex2030"
  name: all
  scenarios:
    enable: true
    file: config/scenarios.flex2030.yaml
  disable_progressbar: false
  shared_resources:
    policy: false #'base'
    exclude: []
  use_shadow_directory: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - 39
  planning_horizons:
  - 2030
  #- 2050
electricity:
  transmission_limit: v1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    tyndp2020: true
    nep: true
    manual: true
  skip:
  - upgraded_lines
  - upgraded_links
  status:
  - under_construction
  #- in_permitting
  #- confirmed
    #- planned_not_yet_permitted
    #- under_consideration
  new_link_capacity: zero #keep or zero

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  shipping: true
  aviation: true
  agriculture: true
  fossil_fuels: true
  district_heating:
    potential: 0.6
    progress:
      2020: 0.0
      2025: 0.1
      2030: 0.0
      2035: 0.4
      2040: 0.55
      2045: 0.75
      2050: 0.0
  bev_dsm: false
  v2g: false
  land_transport_electric_share:
    2030: 0.05
    2040: 0.7
    2050: 0.9
  land_transport_ice_share:
    2030: 0.95
    2040: 0.3
    2050: 0.1
  shipping_methanol_share:
    2030: 0.01
    2040: 0.55
    2050: 0.5
  shipping_oil_share:
    2030: 0.99
    2040: 0.45
    2050: 0.5
  aviation_demand_factor: 1.2
  HVC_demand_factor: 1.0
  reduce_space_heat_exogenously_factor:
    2025: 0.09  # first heat demand increases compared to 2020 because of larger floor area per capita
    2030: 0.09
    2040: 0.16
    2050: 0.09
  tes: false
  solar_thermal: true
  methanation: true
  dac: true
  co2_vent: true
  regional_co2_sequestration_potential:
    enable: false
  co2_sequestration_potential:
    2030: 0
    2040: 180
    2050: 400
  co2_spatial: false
  co2_network: false
  hydrogen_underground_storage: false
  methanol:
    methanol_to_kerosene: true
    biomass_to_methanol: true
    biomass_to_methanol_cc: true
  min_part_load_electrolysis: 0.8
  min_part_load_fischer_tropsch: 0.5
  min_part_load_methanolisation: 0.3
  min_part_load_methanation: 0.3
  use_fischer_tropsch_waste_heat: 0.25
  use_haber_bosch_waste_heat: 0.25
  use_methanolisation_waste_heat: 0.25
  use_methanation_waste_heat: 0.25
  use_fuel_cell_waste_heat: 1
  use_electrolysis_waste_heat: 0.25
  H2_network: false
  biogas_upgrading: true
  biogas_upgrading_cc: true
  biomass_to_liquid: true
  biomass_to_liquid_cc: true
  electrobiofuels: true
  biosng: true
  biosng_cc: true
  bioH2: true
  municipal_solid_waste: true
  solid_biomass_import:
    enable: true
    price: 54 #EUR/MWh
    max_amount: 4000 # TWh
    upstream_emissions_factor: 0 #share of solid biomass CO2 emissions at full combustion

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#industry
industry:
  St_primary_fraction:
    2020: 0.6
    2025: 0.55
    2030: 0.6
    2035: 0.45
    2040: 0.4
    2045: 0.35
    2050: 0.3
  DRI_fraction:
    2020: 0
    2025: 0
    2030: 0
    2035: 0.2
    2040: 0.4
    2045: 0.7
    2050: 1
  H2_DRI: 1.7
  elec_DRI: 0.322
  Al_primary_fraction:
    2020: 0.4
    2025: 0.375
    2030: 0.4
    2035: 0.325
    2040: 0.3
    2045: 0.25
    2050: 0.2
  MWh_NH3_per_tNH3: 5.166
  MWh_CH4_per_tNH3_SMR: 10.8
  MWh_elec_per_tNH3_SMR: 0.7
  MWh_H2_per_tNH3_electrolysis: 5.93
  MWh_elec_per_tNH3_electrolysis: 0.2473
  MWh_NH3_per_MWh_H2_cracker: 1.46 # https://github.com/euronion/trace/blob/44a5ff8401762edbef80eff9cfe5a47c8d3c8be4/data/efficiencies.csv
  NH3_process_emissions: 24.5
  petrochemical_process_emissions: 25.5
  #HVC primary/recycling based on values used in Neumann et al https://doi.org/10.1016/j.joule.2023.06.016, linearly interpolated between 2020 and 2050
  #2020 recycling rates based on Agora https://static.agora-energiewende.de/fileadmin/Projekte/2021/2021_02_EU_CEAP/A-EW_254_Mobilising-circular-economy_study_WEB.pdf
  #fractions refer to the total primary HVC production in 2020
  #assumes 6.7 Mtplastics produced from recycling in 2020
  HVC_primary_fraction:
    2020: 0.88
    2025: 0.85
    2030: 0.88
    2035: 0.7
    2040: 0.6
    2045: 0.5
    2050: 0.6
  HVC_mechanical_recycling_fraction:
    2020: 0.12
    2025: 0.15
    2030: 0.12
    2035: 0.21
    2040: 0.24
    2045: 0.27
    2050: 0.20
  HVC_chemical_recycling_fraction:
    2020: 0.0
    2025: 0.0
    2030: 0.0
    2035: 0.08
    2040: 0.12
    2045: 0.16
    2050: 0.10
  HVC_environment_sequestration_fraction: 0.
  waste_to_energy: true
  waste_to_energy_cc: true
  sector_ratios_fraction_future:
    2020: 0.0
    2025: 0.05
    2030: 0.0
    2035: 0.45
    2040: 0.7
    2045: 0.85
    2050: 0.8
  basic_chemicals_without_NH3_production_today: 69. #Mt/a, = 86 Mtethylene-equiv - 17 MtNH3
  HVC_production_today: 52.
  MWh_elec_per_tHVC_mechanical_recycling: 0.547
  MWh_elec_per_tHVC_chemical_recycling: 6.9
  chlorine_production_today: 9.58
  MWh_elec_per_tCl: 3.6
  MWh_H2_per_tCl: -0.9372
  methanol_production_today: 1.5
  MWh_elec_per_tMeOH: 0.167
  MWh_CH4_per_tMeOH: 10.25
  MWh_MeOH_per_tMeOH: 5.528
  hotmaps_locate_missing: false
  reference_year: 2019
  oil_refining_emissions: 0.013


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2020
  social_discountrate: 0.02
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.07
    "standing losses": 0
  custom_cost_fn: data/custom_costs.csv
  overwrites: {}
  emission_prices:
    enable: false
    co2: 0.
    co2_monthly_prices: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  temporal:
    resolution_sector: "300H"
